routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FbController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ContactController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [Controller::class, 'home'])->name('home');



Route::get('auth/facebook', [FbController::class, 'redirectToFacebook']);
Route::get('auth/facebook/callback', [FbController::class, 'facebookSignin']);

Route::group(['middleware' => ['role:admin']], function () {
    Route::get('admin', [AdminController::class , 'index'])->name('admin');
    Route::resource('admin/users', UsersController::class);
    Route::resource('admin/posts', PostController::class);
    Route::get('/contacts', [ContactController::class, 'GetAll'])->name('contactsAll');
    Route::get('/contact/{id}', [ContactController::class, 'answerEmail'])->name('answerEmail');
    Route::post('/answer_contact/{id}', [ContactController::class, 'sendEmail'])->name('sendEmail');
});

Route::post('/contact_create', [ContactController::class, 'add'])->name('addContact');
Route::get('contact_us/' , [Controller::class , 'contactUs'])->name('contactUs');

Route::get('post/{id}',  [PostController::class , 'single'])->name('single');
require __DIR__.'/auth.php';

resources/views/admin/layouts/app.blade.php
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Admin Panel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

  </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{route('admin')}}">Admin Panel</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{{route('users.index')}}">Users</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{route('posts.index')}}">Posts</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{route('contactsAll')}}">Contacts</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>