routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FbController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ContactController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [Controller::class, 'home'])->name('home');



Route::get('auth/facebook', [FbController::class, 'redirectToFacebook']);
Route::get('auth/facebook/callback', [FbController::class, 'facebookSignin']);

Route::group(['middleware' => ['role:admin']], function () {
    Route::get('admin', [AdminController::class , 'index'])->name('admin');
    Route::resource('admin/users', UsersController::class);
    Route::resource('admin/posts', PostController::class);
    Route::get('/contacts', [ContactController::class, 'GetAll'])->name('contactsAll');
    Route::get('/contact/{id}', [ContactController::class, 'answerEmail'])->name('answerEmail');
    Route::post('/answer_contact/{id}', [ContactController::class, 'sendEmail'])->name('sendEmail');
});

Route::post('/contact_create', [ContactController::class, 'add'])->name('addContact');
Route::get('contact_us/' , [Controller::class , 'contactUs'])->name('contactUs');

Route::get('post/{id}',  [PostController::class , 'single'])->name('single');
require __DIR__.'/auth.php';

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $table = 'posts';

    protected $fillable = [
        'title',
        'description',
        'image_url',
        'author_id',
        ];
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Models\Post;
use Auth;
use Hash;
use File;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::paginate(16);
        
        return view('admin.posts.index')->with('posts', $posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'image_url' => 'required',
        ]);
        
        $file = request()->file('image_url');
        
        $fileName = Hash::make($file);
        Storage::disk('public')->put('images', $file );
        
        $data['image_url'] = $file->hashName();
        $data['author_id'] =Auth::user()->id;
        
        $post = Post::create($data);
        
        $post->save();

        return redirect()->back()->with('msg', 'Post Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);

        return view('admin.posts.edit')->with('post', $post);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::find($id);

        $data = $request->all();

        $request->validate([
            'title' => 'required',
            'description' => 'required',
        ]);
        $post->author_id = Auth::user()->id;
        $post->update($data);

        return redirect()->back()->with('msg', 'Post Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::find($id)->delete();

        return redirect()->back()->with('message','Post deleted successfully');
    }

    public function single($id){
        $post = Post::find($id);

        return view('single')->with('post', $post);
    }

}

resources/views/admin/posts/create.blade.php
@include('admin.layouts.app')

<h1 class="text-center">Add Post</h1>

@if(session()->has('msg'))
    <div class="alert alert-success">
        {{ session()->get('msg') }}
    </div>
@endif
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form style="margin-left: 30%" action="{{route('posts.store')}}" method="POST" enctype="multipart/form-data" >
    {{ csrf_field() }} 
    
  
    <div class="mb-3">
          <label for="title" class="form-label align-self-center">Title</label>
          <input type="text" class="form-control w-50" name="title"  id="title" >
        
        </div>
        <div class="mb-3">
            <label for="image">Choose Image</label>
            <input id="image" type="file" name="image_url">
          
          </div>
      <div class="mb-3">
        <label  for="description" class="form-label align-self-center">Description</label>
        <textarea  type="text" class="form-control w-50" name="description"  id="ckeditor" ></textarea>
      </div>
     
    
       <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <script type="text/javascript">
        $(document).ready(function () {
           var editor =  CKEDITOR.replace( 'ckeditor' );
    
        });
    </script>

resources/views/admin/posts/edit.blade.php
@include('admin.layouts.app')

<h1 class="text-center">Edit Post</h1>

@if(session()->has('msg'))
    <div class="alert alert-success">
        {{ session()->get('msg') }}
    </div>
@endif
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form style="margin-left: 30%" action="{{route('posts.update', $post->id)}}" method="POST">
    @csrf
    @method('PUT')
  
    <div class="mb-3">
          <label for="title" class="form-label align-self-center">Title</label>
          <input type="text" class="form-control w-50" value="{{$post->title}}" name="title"  id="title" >
        
        </div>
      <div class="mb-3">
        <label  for="description" class="form-label align-self-center">Description</label>
        <textarea  type="text" class="form-control w-50" name="description"  id="ckeditor">{{$post->description}}</textarea>
      </div>
     
    
       <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <script type="text/javascript">
        $(document).ready(function () {
           var editor =  CKEDITOR.replace( 'ckeditor' );
    
        });
    </script>

resources/views/admin/posts/index.blade.php
@include('admin.layouts.app')
<h1>Posts </h1>
<a href="{{route('posts.create')}}" class="btn btn-outline-success  m-3">Create A Post</a>
 
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Author ID</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
@foreach ($posts as $item)
<tr>
    <th scope="row">{{$item->id}}</th>
   
    <td>{{$item->title}}</td>
    <td style="">{{ strip_tags($item->description) }}</td>
    <td>{{$item->author_id}}</td>
    <td class="d-flex">
      <a class="btn btn-warning" style="    height: 37px;" href="{{route('posts.edit', $item->id)}}" role="button">Edit</a>
      <form style="margin-left: 10px" action="{{route('posts.destroy', $item->id)}}" method="POST">
        @csrf
        @method("DELETE")
        <button type="submit" class="btn btn-danger">Delete</button>

      </form>
    </td>
  </tr>
@endforeach
    </tbody>